#!/usr/bin/env python3
"""
scripts/tradeoff_scatter.py

Purpose:
- Generate the trade-off scatter plot (ΔHR_TQA vs Δacc_norm) from the lightweight delta CSV.

Inputs:
- evals/comparison/delta_summary_for_plots.csv
  (generated by scripts/export_delta_summary_for_plots.py)

Outputs:
- docs/figures/tradeoff_scatter.png
- docs/figures/tradeoff_scatter.pdf

Notes:
- The plot uses percentage points (pp): pp = delta * 100.
- ΔHR_TQA is a hallucination-rate proxy delta (HR_TQA = 1 - acc(MC2)); lower is better.
- Δacc_norm (ARC-Easy) is a utility proxy delta; higher is better.

Determinism / reruns:
- Plot is fully deterministic given the input CSV.
"""

import csv
from pathlib import Path

import matplotlib.pyplot as plt


def load_points(csv_path: Path) -> list[tuple[str, float, float]]:
    # Load (adapter, ΔHR_TQA_pp, Δacc_norm_pp) from the delta CSV.
    if not csv_path.is_file():
        raise FileNotFoundError(
            f"Missing CSV: {csv_path}. Run scripts/export_delta_summary_for_plots.py first."
        )

    points: list[tuple[str, float, float]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {"adapter", "delta_hr_truthfulqa", "delta_acc_norm_arc"}
        if not required.issubset(reader.fieldnames or []):
            raise ValueError(f"CSV missing required columns: {required}. Found: {reader.fieldnames}")

        for row in reader:
            name = row["adapter"].strip()
            dx = float(row["delta_hr_truthfulqa"]) * 100.0   # percentage points
            dy = float(row["delta_acc_norm_arc"]) * 100.0    # percentage points
            points.append((name, dx, dy))

    if not points:
        raise RuntimeError(f"No rows found in {csv_path}")

    return points


def main() -> None:
    csv_path = Path("evals") / "comparison" / "delta_summary_for_plots.csv"
    points = load_points(csv_path)

    x = [p[1] for p in points]
    y = [p[2] for p in points]

    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    ax.scatter(x, y, s=80)

    for name, xi, yi in points:
        ax.annotate(name, (xi, yi), textcoords="offset points", xytext=(6, 6), ha="left", fontsize=10)

    ax.axvline(0, linewidth=1)
    ax.axhline(0, linewidth=1)

    ax.set_xlabel("ΔHR_TQA (pp)")
    ax.set_ylabel("ΔU = Δacc_norm (pp)")
    ax.set_title("Trade-off veracidad–utilidad por adaptador (pre vs post QLoRA)")

    ax.set_xlim(min(x) - 1.0, max(x) + 1.0)
    ax.set_ylim(min(y) - 0.5, max(y) + 0.5)
    ax.grid(True, linestyle="--", linewidth=0.5)

    plt.tight_layout()

    out_dir = Path("docs") / "figures"
    out_dir.mkdir(parents=True, exist_ok=True)

    png_path = out_dir / "tradeoff_scatter.png"
    pdf_path = out_dir / "tradeoff_scatter.pdf"

    plt.savefig(png_path, dpi=600, bbox_inches="tight")
    plt.savefig(pdf_path, bbox_inches="tight")

    print(f"[tradeoff_scatter] Loaded: {csv_path}")
    print(f"[tradeoff_scatter] Saved:  {png_path}")
    print(f"[tradeoff_scatter] Saved:  {pdf_path}")

    plt.show()


if __name__ == "__main__":
    main()
